before:
  hooks:
    - go mod tidy

###
# Builds
###

builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
      # - v2
      # - v3
      # - v4
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/helmwave
    ldflags:
      - -s -w -X github.com/helmwave/helmwave/pkg/version.Version={{.Version}}

###
# Packages
###

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

dockers:
  - dockerfile: Dockerfile
    image_templates:
      - "ghcr.io/helmwave/helmwave:{{ .Version }}-scratch"
      - "ghcr.io/helmwave/helmwave:scratch"

      - "diamon/helmwave:{{ .Version }}-scratch"
      - "diamon/helmwave:scratch"
    build_flag_templates:
      - "--label=org.opencontainers.image.description=Helmwave is tool for deploy your Helm Charts via GitOps"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.source=https://github.com/helmwave/helmwave"
      - "--label=org.opencontainers.image.url=https://github.com/helmwave/helmwave/pkgs/container/helmwave"
      - "--label=org.opencontainers.image.documentation=https://helmwave.github.io/docs/"

      - "--platform=linux/amd64"
      - "--target=scratch-goreleaser"
      - "--pull"
    goos: linux
    goarch: amd64
    use: buildx
  - dockerfile: Dockerfile
    image_templates:
      - "ghcr.io/helmwave/helmwave:{{ .Version }}"
      - "ghcr.io/helmwave/helmwave:latest"

      - "diamon/helmwave:{{ .Version }}"
      - "diamon/helmwave:latest"
    build_flag_templates:
      - "--label=org.opencontainers.image.description=Helmwave is tool for deploy your Helm Charts via GitOps"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.source=https://github.com/helmwave/helmwave"
      - "--label=org.opencontainers.image.url=https://github.com/helmwave/helmwave/pkgs/container/helmwave"
      - "--label=org.opencontainers.image.documentation=https://helmwave.github.io/docs/"

      - "--platform=linux/amd64"
      - "--target=goreleaser"
      - "--pull"
    goos: linux
    goarch: amd64
    use: buildx

###
# Publishes
###

changelog:
  skip: false
  use: github
  sort: asc

  groups:
    - title: "Linter"
      regexp: "^.*linter.*$"
      order: 1
    - title: "Tests"
      regexp: "^.*tests?.*$"
      order: 2
    - title: "Bump"
      regexp: "^.*[bB]ump?.*$"
      order: 3
    - title: "Dependencies"
      regexp: "^.*(deps):.*$"
      order: 4
    - title: "CI"
      regexp: "^.*(ci):.*$"
      order: 5
    - title: "New Features"
      regexp: "^feat[(\\w)]*:.*$"
      order: 0
    - title: "Other"
      order: 999

  filters:
    exclude:
      - "^WIP:"
      - Merge pull request
      - Merge branch
      - go mod tidy
      - typo

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  name_template: "v{{ .Version }}"
  #  draft: true
  prerelease: auto

brews:
  - tap:
      owner: helmwave
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    description: "HelmWave is like docker-compose for helm"
    license: "MIT"
    folder: formula
    skip_upload: auto

milestones:
  - repo:
      owner: helmwave
      name: helmwave
    close: true
    fail_on_error: false
    name_template: "{{.Tag}}"
