before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
      - GO386=softfloat
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: darwin
        goarch: 386
    main: ./cmd/helmwave
    ldflags:
      - -s -w -X github.com/zhilyaev/helmwave/pkg/helmwave.Version={{.Version}}

archives:
  - format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  name_template: "Release v{{.Version}}"
  draft: true
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'


dockers:
  - image_templates:
      - "zhilyaev/helmwave/helmwave:{{ .Tag }}"
      - "zhilyaev/helmwave/helmwave:latest"
    goos: linux
    goarch: amd64
    use_buildx: true

brews:
  - tap:
      owner: zhilyaev
      name: helmwave
    folder: formula
    description: "Software to create fast and easy drum rolls."
    license: "MIT"


