name: Lint

on:
  push:
    branches:
      - master
      - main
      - release*
  pull_request:

jobs:
  golangci:
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - 1.15.x
          - 1.16.x
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          args: --timeout=5m --disable=gosimple,deadcode,unused

