name: Go lint

on:
  push:
    paths:
      - "**.go"
      - .github/workflows/go-lint.yml
      - .golangci.yml

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - 1.18.x
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.45.0
