name: Run tests against KinD cluster

on: pull_request

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Create KinD cluster
        uses: container-tools/kind-action@v1
        with:
          registry: false

      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install go modules
        run: go mod download

# TODO: remove this hack (see issue #70)
      - name: Create helm dir
        run: mkdir -p ~/.helm/repository

      - name: Run integration tests
        run: go test -v ./tests/integration