name: Run tests against KinD cluster

on: pull_request

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Create KinD cluster
        uses: container-tools/kind-action@v1
        with:
          registry: false

      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Run integration tests
        run: go test -v ./tests/integration