name: LGTM
on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: micnncim/action-lgtm-reaction@v0.6.0
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}