name: Notify

on:
  release:
    types: [published]

jobs:
  telegram:
    runs-on: ubuntu-latest
    steps:
    - name: Set GITHUB_TAG
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Telegram
      uses: appleboy/telegram-action@master
      env:
        GITHUB_TAG: ${{ steps.vars.outputs.tag }}
      with:
        to: ${{ secrets.CHAT }}
        token: ${{ secrets.BOT_TOKEN }}
        format: markdown
        message: |
          Helmwave *${{ env.GITHUB_TAG }}* is ready!
          See more: https://github.com/helmwave/helmwave/releases/tag/${{ env.GITHUB_TAG }}
