name: Notify

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Helmwave tag to notify about"
        required: true
        type: string

jobs:
  telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Telegram
        uses: appleboy/telegram-action@master
        env:
          GITHUB_TAG: ${{ inputs.tag }}
        with:
          to: ${{ secrets.CHAT }}
          token: ${{ secrets.BOT_TOKEN }}
          format: markdown
          message: |
            Helmwave *${{ env.GITHUB_TAG }}* is ready!
            See more: https://github.com/helmwave/helmwave/releases/tag/${{ env.GITHUB_TAG }}

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger helmwave/docs workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: "docs",
              workflow_id: "generate-new-version.yml",
              ref: "main",
              inputs: {
                tag: process.env.GITHUB_TAG,
              },
            })
        env:
          GITHUB_TAG: ${{ inputs.tag }}
